REPLACE INTO `s_core_snippets` (`namespace`, `name`, `value`, `localeID`, `shopID`,`created`, `updated`) VALUES
('Paymill', 'version', 'Version', '2', '2', NOW(), NOW()),
('Paymill', 'date', 'Date', '2', '2', NOW(), NOW()),
('Paymill', 'devinfo', 'Developerinformation', '2', '2', NOW(), NOW()),
('Paymill', 'additionaldevinfo', 'Additional Developerinformation', '2', '2', NOW(), NOW()),
('Paymill', 'action', 'Action', '2', '2', NOW(), NOW()),
('Paymill', 'merchantinfo', 'Merchantinfo', '2', '2', NOW(), NOW()),
('Paymill', 'invalid_cardnumber', 'Please enter a valid creditcardnumber.', '2', '2', NOW(), NOW()),
('Paymill', 'invalid_cvc', 'Please enter a valid securecode (see back of creditcard).', '2', '2', NOW(), NOW()),
('Paymill', 'invalid_expirydate', 'The expirydate is invalid.', '2', '2', NOW(), NOW()),
('Paymill', 'invalid_accountholder', 'Please enter the cardholders name.', '2', '2', NOW(), NOW()),
('Paymill', 'invalid_accountnumber', 'Please enter a valid accountnumber.', '2', '2', NOW(), NOW()),
('Paymill', 'invalid_bankcode', 'Please a valid bankcode.', '2', '2', NOW(), NOW()),
('Paymill', 'invalid_error_creditcard', 'Please enter your creditcarddata. For security reason we will not save them on our system.', '2', '2', NOW(), NOW()),
('Paymill', 'invalid_error_debit', 'Please enter your accountdata. For security reason we will not save them on our system.', '2', '2', NOW(), NOW()),
('Paymill', 'form_cardholder', 'Cardholder *', '2', '2', NOW(), NOW()),
('Paymill', 'form_cardnumber', 'Cardnumber *', '2', '2', NOW(), NOW()),
('Paymill', 'form_cvc', 'CVC *', '2', '2', '2013-06-25 17:29:18', NOW()),
('Paymill', 'form_expirydate', 'Valid until (MM/YYYY) *', '2', '2', NOW(), NOW()),
('Paymill', 'form_accountholder', 'Accountholder *', '2', '2', NOW(), NOW()),
('Paymill', 'form_accountnumber', 'Accountnumber *', '2', '2', NOW(), NOW()),
('Paymill', 'form_bankcode', 'Bankcode *', '2', '2', NOW(), NOW()),
('Paymill', 'form_info', 'Fields marked with a * are required.', '2', '2', NOW(), NOW()),
('Paymill', 'form_paymilllabel_cc', 'Secure creditcardpayment powered by', '2', '2', NOW(), NOW()),
('Paymill', 'form_paymilllabel_debit', 'Secure directdebitpayment powered by', '2', '2', NOW(), NOW());